#!/bin/bash

# Script tự động tạo proxy trên Ubuntu server với aapanel
# Yêu cầu: Không cần tham số, dừng lại khi cần lựa chọn

set -e

# Hàm kiểm tra và cài đặt 3proxy nếu chưa có
install_3proxy() {
    if ! command -v 3proxy &> /dev/null; then
        echo "Cài đặt 3proxy từ source..."
        apt update
        apt install -y build-essential git
        git clone https://github.com/z3APA3A/3proxy.git /tmp/3proxy
        cd /tmp/3proxy
        make
        make install
        mkdir -p /etc/3proxy
    else
        echo "3proxy đã được cài đặt."
    fi
}

# Hàm tạo random user và password
generate_credentials() {
    local user="user$(shuf -i 1000-9999 -n 1)"
    local pass="pass$(shuf -i 1000-9999 -n 1)"
    echo "$user:$pass"
}

# Hàm lấy IP của server
get_ip() {
    curl -s ifconfig.me
}

# Hàm kiểm tra số lượng proxy tối đa có thể tạo
check_max_proxies() {
    # Giả sử dựa trên port available, từ 3128 trở lên
    local used_ports=$(netstat -tlnp 2>/dev/null | awk '{print $4}' | grep -o ':3[0-9][0-9][0-9]$' | wc -l)
    local max_ports=1000  # Giới hạn giả định
    echo $((max_ports - used_ports))
}

# Hàm tạo proxy
create_proxy() {
    local num_proxies=$1
    local ip_version=$2
    local config_file="/etc/3proxy/3proxy.cfg"
    local output_file="proxies.txt"
    local ip=$(get_ip)

    # Sao lưu config cũ nếu có
    if [ -f "$config_file" ]; then
        cp "$config_file" "${config_file}.bak"
    fi

    # Tạo config mới
    echo "# 3proxy config generated by script" > "$config_file"
    echo "nserver 8.8.8.8" >> "$config_file"
    echo "nserver 8.8.4.4" >> "$config_file"
    echo "nscache 65536" >> "$config_file"
    echo "timeouts 1 5 30 60 180 1800 15 60" >> "$config_file"

    local port=3128
    for ((i=1; i<=num_proxies; i++)); do
        local creds=$(generate_credentials)
        local user=$(echo $creds | cut -d: -f1)
        local pass=$(echo $creds | cut -d: -f2)
        echo "users $user:CL:$pass" >> "$config_file"
        echo "socks -p$port -i0.0.0.0 -u$user" >> "$config_file"
        echo "$ip:$port:$user:$pass" >> "$output_file"
        ((port++))
    done

    # Khởi động lại 3proxy
    systemctl restart 3proxy 2>/dev/null || service 3proxy restart 2>/dev/null || echo "Không thể restart 3proxy, vui lòng restart thủ công."

    echo "Proxy đã được tạo. Thông tin lưu trong $output_file"
    cat "$output_file"
}

# Main script
echo "Chào mừng đến với script tạo proxy tự động."
echo "Script này sẽ cài đặt các thư viện cần thiết và tạo proxy."

# Cài đặt 3proxy
install_3proxy

# Kiểm tra số lượng proxy tối đa
max_proxies=$(check_max_proxies)
echo "Máy chủ có thể tạo tối đa $max_proxies proxy."

# Nhập số lượng proxy
read -p "Nhập số lượng proxy cần tạo (tối đa $max_proxies): " num_proxies
if ! [[ "$num_proxies" =~ ^[0-9]+$ ]] || [ "$num_proxies" -le 0 ] || [ "$num_proxies" -gt "$max_proxies" ]; then
    echo "Số lượng không hợp lệ."
    exit 1
fi

# Chọn phiên bản IP
echo "Chọn phiên bản IP:"
echo "1. IPv4"
echo "2. IPv6"
read -p "Lựa chọn (1 hoặc 2): " ip_choice
if [ "$ip_choice" == "1" ]; then
    ip_version="ipv4"
elif [ "$ip_choice" == "2" ]; then
    ip_version="ipv6"
else
    echo "Lựa chọn không hợp lệ."
    exit 1
fi

# Tạo proxy
create_proxy "$num_proxies" "$ip_version"

echo "Hoàn tất. Nếu chạy lại script, proxy mới sẽ được thêm vào file proxies.txt."
